version: "3.7"
services:
    mysql:
        build: ./mysql
        networks:
            - nt
    sinatra:
        build: ./sinatra
        volumes:
             - "./sinatra:/app"
        ports: 
            - "9292:9292"
        networks:
            - nt
        depends_on:
        - mysql
    next-js:
        build: ./next-js
        volumes:
            - "./next-js:/app"
            - "/app/node_modules"
            - "/app/.next"
        ports:
            - "80:3000"
        networks:
            - nt
        depends_on:
            - sinatra
networks:
    nt:
        driver: bridge
